/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import core.CarInventorySystem;
import core.Vehicle;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Brandon
 */
public class SearchInventoryUI extends javax.swing.JPanel {
    
    boolean unitTesting = true;
    

    /**
     * Creates new form SearchInventoryUI
     */
    public SearchInventoryUI() {
        initComponents();
        jTextArea1.setEditable(false);
        jPanel1.setVisible(true);
        
        // Adds an "OK" and "CANCEL" dialog
        int result = JOptionPane.showConfirmDialog(null, this, "Search Inventory",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        
        // Logic for OKAY or CANCEL button press
        if (result == JOptionPane.OK_OPTION) 
        {

            // When OK is pressed, input logic here to store data to database
            // BUG: All input fields must be entered or application will crash
            // TODO: Check user input. Before closing. Must be implemented with a custom dialog
//            String first = firstNameField.getText();
//            String last = lastNameField.getText();
//            int age = Integer.parseInt(ageField.getText());
//            String email = emailField.getText();
//            String phone = phoneField.getText();
            
            // For debugging purposes:
            // System.out.println(first + " " + last);
            
            if(ValidateInput()) {
                //int searchID = Integer.parseInt(searchIDField.getText());
                
                //KEEP these lines
//                if(!unitTesting) {
//                    CarInventorySystem inventory = new CarInventorySystem();
//                    Vehicle foundVehicle = inventory.SearchVehicle(searchID);
//                
//                    if(foundVehicle != null) {
//                        JOptionPane.showMessageDialog(null, "Found vehicle: " + 
//                                foundVehicle.getYear() + " " + foundVehicle.getMake() + 
//                                " " + foundVehicle.getModel() + " " + 
//                                foundVehicle.getColor() + " " + 
//                                foundVehicle.getCarClass() + " for a daily price of $" + 
//                                foundVehicle.getDailyPrice(), "Vehicle Found", 
//                                JOptionPane.INFORMATION_MESSAGE);
//                    }
//                    else {
//                        JOptionPane.showMessageDialog(null, 
//                                "Error: The requested vehicle was not found. "
//                                        + "Please try again.", "Error", 
//                                        JOptionPane.ERROR_MESSAGE);
//                    }
//                }
            }
            else {
                JOptionPane.showMessageDialog(null, "The field is blank. "
                        + "Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            
//            Customer addedCustomer = new Customer();
//            addedCustomer.setFirstName(first);
//            addedCustomer.setLastName(last);
//            addedCustomer.setAge(age);
//            addedCustomer.setPhoneNumber(phone);
//            addedCustomer.setEmailAddress(email);
//            addedCustomer.StoreCustomer();
            
//            CustomerStorageSystem customerSystem = new CustomerStorageSystem();
//            customerSystem.RegisterCustomer(first, last, age, phone, email);
        } 
        else 
        {
            System.out.println("Cancelled");
        }
    }
    
    private boolean ValidateInput() {
        return !searchIDField.getText().isEmpty();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchIDField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        jLabel1.setText("Search by...");

        searchIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIDFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Make", "Model", "Year", "Class", "Color" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(searchIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jButton1)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jScrollPane3.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchIDFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           
        //Currently only lists one item
        //Also lots of formatting to be done
        
        
        
            String comboInput = jComboBox1.getSelectedItem().toString();
            int i=0;
            Vehicle arrayElement;
            int size = CarInventorySystem.getSize();
            boolean flag = false;
            ArrayList<Vehicle> searchResults = new ArrayList();
            
            if(comboInput.equals("ID")){
                int id = Integer.parseInt(searchIDField.getText());
                arrayElement = CarInventorySystem.getCar(id);
                searchResults.add(arrayElement);
                flag = true;
            }
            else if(comboInput.equals("Make")){
                String make = searchIDField.getText();
                for(i=0;i<size;i++){
                    arrayElement = CarInventorySystem.getCar(i);
                    System.out.println(arrayElement.getMake());
                    if(arrayElement.getMake().equals(make)){
                        /*jTextArea1.setText(arrayElement.getID() + ": " + arrayElement.getColor() + " "  + arrayElement.getYear()
                                            + " " + arrayElement.getMake() + " " + arrayElement.getModel());
                        */
                        searchResults.add(arrayElement);
                        flag = true;
                    }

                }
            }
            else if(comboInput.equals("Model")){
                String model = searchIDField.getText();
                for(i=0;i<size;i++){
                    arrayElement = CarInventorySystem.getCar(i);
                    System.out.println(arrayElement.getModel());
                    if(arrayElement.getModel().equals(model)){
                        searchResults.add(arrayElement);
                        flag = true;
                    }
                    
                }
            }
            else if(comboInput.equals("Year")){
                int year = Integer.parseInt(searchIDField.getText());
                for(i=0;i<size;i++){
                    arrayElement = CarInventorySystem.getCar(i);
                    System.out.println(arrayElement.getYear());
                    if(arrayElement.getYear() == year){
                        searchResults.add(arrayElement);
                        flag = true;
                    }

                }
            }
            else if(comboInput.equals("Class")){
                String carClass = searchIDField.getText();
                for(i=0;i<size;i++){
                    arrayElement = CarInventorySystem.getCar(i);
                    System.out.println(arrayElement.getCarClass());
                    if(arrayElement.getCarClass().equals(carClass)){
                        searchResults.add(arrayElement);
                        flag = true;
                    }

                }
            }
            else if(comboInput.equals("Color")){
                String color = searchIDField.getText();
                for(i=0;i<size;i++){
                    arrayElement = CarInventorySystem.getCar(i);
                    System.out.println(arrayElement.getColor());
                    if(arrayElement.getColor().equals(color)){
                        searchResults.add(arrayElement);
                        flag = true;
                    }
                   
                }
            }
            
            if(flag == true){
                for(i=0;i<searchResults.size();i++){
                    jTextArea1.setText(searchResults.size() + " result(s) found:\n\n" );
                    jTextArea1.append("Vehicle ID: " + searchResults.get(i).getID() + "\n");
                    jTextArea1.append("Make: " + searchResults.get(i).getMake() + "\n");
                    jTextArea1.append("Model: " + searchResults.get(i).getModel() + "\n");
                    jTextArea1.append("Year: " + searchResults.get(i).getYear() + "\n");
                    jTextArea1.append("Color: " + searchResults.get(i).getColor() + "\n");

                
                }
            }
            else{
                jTextArea1.setText("No car found");
            }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextField searchIDField;
    // End of variables declaration//GEN-END:variables
}
