package userInterface;

import core.*;
import Rentacar.*;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

public class RentacarUI extends javax.swing.JFrame
{
    /**
     * Creates new form RentacarUI
     */
    public RentacarUI()
    {
        initComponents();
        
        // Scan whole DB every day for possible vehicles that need maintenance
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenuItem10 = new javax.swing.JMenuItem();
        welcomeLabel = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        rentButton = new javax.swing.JButton();
        maintenanceButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        quitMenuItem = new javax.swing.JMenuItem();
        rentalsMenu = new javax.swing.JMenu();
        newRentalMenu = new javax.swing.JMenuItem();
        newReturnRentalMenu = new javax.swing.JMenuItem();
        viewRentalMenu = new javax.swing.JMenuItem();
        inventoryMenu = new javax.swing.JMenu();
        addInventoryMenuItem = new javax.swing.JMenuItem();
        searchInventoryMenuItem = new javax.swing.JMenuItem();
        updateInventoryMenuItem = new javax.swing.JMenuItem();
        viewInventoryMenuItem = new javax.swing.JMenuItem();
        customerDataMenu = new javax.swing.JMenu();
        addCustomerMenuItem = new javax.swing.JMenuItem();
        searchCustomerMenuItem = new javax.swing.JMenuItem();
        updateCustomerMenuItem = new javax.swing.JMenuItem();
        viewCustomerMenuItem = new javax.swing.JMenuItem();

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        welcomeLabel.setText("Welcome to Rent-a-Car");

        returnButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        returnButton.setText("Return a car");
        returnButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                returnButtonActionPerformed(evt);
            }
        });

        rentButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rentButton.setText("Rent a car");
        rentButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rentButtonActionPerformed(evt);
            }
        });

        maintenanceButton.setText("Maintenance");
        maintenanceButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                maintenanceButtonActionPerformed(evt);
            }
        });

        fileMenu.setText("File");

        quitMenuItem.setText("Quit");
        quitMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                quitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(quitMenuItem);

        menuBar.add(fileMenu);

        rentalsMenu.setText("Rentals");

        newRentalMenu.setText("New Rental...");
        newRentalMenu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newRentalMenuActionPerformed(evt);
            }
        });
        rentalsMenu.add(newRentalMenu);

        newReturnRentalMenu.setText("Return Rental...");
        newReturnRentalMenu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newReturnRentalMenuActionPerformed(evt);
            }
        });
        rentalsMenu.add(newReturnRentalMenu);

        viewRentalMenu.setText("View Rental...");
        viewRentalMenu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                viewRentalMenuActionPerformed(evt);
            }
        });
        rentalsMenu.add(viewRentalMenu);

        menuBar.add(rentalsMenu);

        inventoryMenu.setText("Inventory");

        addInventoryMenuItem.setText("Add inventory...");
        addInventoryMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addInventoryMenuItemActionPerformed(evt);
            }
        });
        inventoryMenu.add(addInventoryMenuItem);

        searchInventoryMenuItem.setText("Search Inventory...");
        searchInventoryMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                searchInventoryMenuItemActionPerformed(evt);
            }
        });
        inventoryMenu.add(searchInventoryMenuItem);

        updateInventoryMenuItem.setText("Update Inventory...");
        updateInventoryMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                updateInventoryMenuItemActionPerformed(evt);
            }
        });
        inventoryMenu.add(updateInventoryMenuItem);

        viewInventoryMenuItem.setText("View Inventory...");
        inventoryMenu.add(viewInventoryMenuItem);

        menuBar.add(inventoryMenu);

        customerDataMenu.setText("Customer Data");

        addCustomerMenuItem.setText("Add customer...");
        addCustomerMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addCustomerMenuItemActionPerformed(evt);
            }
        });
        customerDataMenu.add(addCustomerMenuItem);

        searchCustomerMenuItem.setText("Search customer...");
        searchCustomerMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                searchCustomerMenuItemActionPerformed(evt);
            }
        });
        customerDataMenu.add(searchCustomerMenuItem);

        updateCustomerMenuItem.setText("Update customer...");
        updateCustomerMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                updateCustomerMenuItemActionPerformed(evt);
            }
        });
        customerDataMenu.add(updateCustomerMenuItem);

        viewCustomerMenuItem.setText("View customers...");
        viewCustomerMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                viewCustomerMenuItemActionPerformed(evt);
            }
        });
        customerDataMenu.add(viewCustomerMenuItem);

        menuBar.add(customerDataMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(welcomeLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(maintenanceButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(maintenanceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Code when newRental menu is pressed
    private void newRentalMenuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newRentalMenuActionPerformed
    {//GEN-HEADEREND:event_newRentalMenuActionPerformed
        try {
            new newRentalUI();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RentacarUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newRentalMenuActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_returnButtonActionPerformed
    {//GEN-HEADEREND:event_returnButtonActionPerformed
        new ReturnCarUI();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void rentButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rentButtonActionPerformed
    {//GEN-HEADEREND:event_rentButtonActionPerformed
        try {
            new newRentalUI();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RentacarUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rentButtonActionPerformed

    private void addInventoryMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addInventoryMenuItemActionPerformed
    {//GEN-HEADEREND:event_addInventoryMenuItemActionPerformed
        try {
            new NewVehicleUI();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RentacarUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addInventoryMenuItemActionPerformed

    private void updateInventoryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInventoryMenuItemActionPerformed
        try {
            new UpdateVehicleUI();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RentacarUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateInventoryMenuItemActionPerformed

    private void addCustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerMenuItemActionPerformed
        try {
            new NewCustomerUI();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RentacarUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addCustomerMenuItemActionPerformed

    private void quitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitMenuItemActionPerformed

    private void updateCustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerMenuItemActionPerformed
        try {
            new UpdateCustomerUI();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RentacarUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateCustomerMenuItemActionPerformed

    private void viewCustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomerMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewCustomerMenuItemActionPerformed

    private void searchCustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerMenuItemActionPerformed
        new SearchCustomerUI();
        
    }//GEN-LAST:event_searchCustomerMenuItemActionPerformed

    private void searchInventoryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInventoryMenuItemActionPerformed
        new SearchInventoryUI();
    }//GEN-LAST:event_searchInventoryMenuItemActionPerformed

    private void newReturnRentalMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newReturnRentalMenuActionPerformed
        new ReturnCarUI();
    }//GEN-LAST:event_newReturnRentalMenuActionPerformed

    private void viewRentalMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRentalMenuActionPerformed
        new ViewRentalsUI();
    }//GEN-LAST:event_viewRentalMenuActionPerformed

    private void maintenanceButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_maintenanceButtonActionPerformed
    {//GEN-HEADEREND:event_maintenanceButtonActionPerformed
        new MaintenanceReminderUI();
    }//GEN-LAST:event_maintenanceButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addCustomerMenuItem;
    private javax.swing.JMenuItem addInventoryMenuItem;
    private javax.swing.JMenu customerDataMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu inventoryMenu;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JButton maintenanceButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newRentalMenu;
    private javax.swing.JMenuItem newReturnRentalMenu;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JButton rentButton;
    private javax.swing.JMenu rentalsMenu;
    private javax.swing.JButton returnButton;
    private javax.swing.JMenuItem searchCustomerMenuItem;
    private javax.swing.JMenuItem searchInventoryMenuItem;
    private javax.swing.JMenuItem updateCustomerMenuItem;
    private javax.swing.JMenuItem updateInventoryMenuItem;
    private javax.swing.JMenuItem viewCustomerMenuItem;
    private javax.swing.JMenuItem viewInventoryMenuItem;
    private javax.swing.JMenuItem viewRentalMenu;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
