package userInterface;

import core.CarInventorySystem;
import core.Customer;
import core.Vehicle;
import core.CustomerStorageSystem;
import javax.swing.JOptionPane;

public class SearchCustomerUI extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer SearchCustomer
     */
    public SearchCustomerUI() {
        initComponents();
        
        int result = JOptionPane.showConfirmDialog(null, this, "Search Inventory",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstnameField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lastnameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        firstnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        lastnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("First name");

        jLabel3.setText("Last name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lastnameField)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.LINE_END);
        add(jScrollPane3, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String firstname = firstnameField.getText();
        String lastname = lastnameField.getText();
        int i;
        int size = CustomerStorageSystem.getSize();
        Customer customer;
        
        for(i=0;i<size;i++){
            customer = CustomerStorageSystem.getCustomer(i);
            if(customer.getFirstName().equals(firstname) && customer.getLastName().equals(lastname)){
                if(customer.getRentalID() == -1){
                    jTextArea1.setText("Customer Information:\n");
                    jTextArea1.append("Name: " + customer.getFirstName() + " " + customer.getLastName() + "/n");
                    jTextArea1.append("Email: " +  customer.getEmailAddress() + "\n");
                    jTextArea1.append("Phone Number: " + customer.getPhoneNumber() + "\n\n");
                    jTextArea1.append("Current Rental: \nNONE");
                    
                    
                }
                else{
                    Vehicle rental = CarInventorySystem.getCar(customer.getRentalID());
                    jTextArea1.setText("Customer Information:\n");
                    jTextArea1.append("Name: " + customer.getFirstName() + " " + customer.getLastName() + "\n");
                    jTextArea1.append("Email: " +  customer.getEmailAddress() + "\n");
                    jTextArea1.append("Phone Number: " + customer.getPhoneNumber() + "\n\n");
                    jTextArea1.append("Current Rental: \n");
                    
                    jTextArea1.append("Vehicle ID: " + rental.getID() + "\n");
                    jTextArea1.append("Make: " + rental.getMake() + "\n");
                    jTextArea1.append("Model: " + rental.getModel() + "\n");
                    jTextArea1.append("Year: " + rental.getYear() + "\n");
                    jTextArea1.append("Color: " + rental.getColor() + "\n");
                }/*
                if(customer.getRentalID() == -1){
                    jTextArea1.setText(customer.getFirstName() + " " + customer.getLastName() + " " + 
                            customer.getEmailAddress() + " " + customer.getPhoneNumber());
                }
                else{
                    Vehicle rental = CarInventorySystem.getCar(customer.getRentalID());
                    jTextArea1.setText(customer.getFirstName() + " " + customer.getLastName() + " " + 
                            customer.getEmailAddress() + " " + customer.getPhoneNumber() + "\n" +
                           rental.getID() + ": " + rental.getColor() + " " + rental.getYear() + " " + 
                            rental.getMake() + " "  + rental.getModel());
                }
*/
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lastnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField firstnameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lastnameField;
    // End of variables declaration//GEN-END:variables
}
